version: "3.2"
services:
  php:
    build: "./php/"
    networks:
      - backend
    volumes:
      - ./web/:/var/www/html/
  apache:
    build: "./apache/"
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8082:80"
    volumes:
      - ./web/:/var/www/html/
networks:
  frontend:
  backend:
